#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generate comprehensive Pester code coverage reports.

.DESCRIPTION
    Analyzes Pester code coverage results and generates:
    - Detailed text-based coverage summary
    - HTML interactive coverage report
    - Coverage metrics and statistics
    - Identification of untested code paths

.PARAMETER CoverageXmlPath
    Path to the coverage.xml file generated by Pester (CoverageGutters format).

.PARAMETER OutputPath
    Directory where reports will be generated. Default: ./results

.PARAMETER Format
    Report formats to generate. Options: Html, Text, All. Default: All

.PARAMETER Threshold
    Minimum coverage percentage threshold (0-100). Warnings will be generated for
    coverage below this percentage. Default: 80

.PARAMETER IncludeUntested
    If specified, includes detailed list of untested code paths in the report.

.EXAMPLE
    .\Generate-CoverageReport.ps1 -CoverageXmlPath ".\results\coverage.xml"
    Generates both HTML and text coverage reports.

.EXAMPLE
    .\Generate-CoverageReport.ps1 -CoverageXmlPath ".\results\coverage.xml" -Format Html -Threshold 85
    Generates HTML report only with 85% coverage threshold.

.EXAMPLE
    .\Generate-CoverageReport.ps1 -CoverageXmlPath ".\results\coverage.xml" -IncludeUntested
    Generates reports with detailed untested code paths.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateScript({ Test-Path -LiteralPath $_ })]
    [string]$CoverageXmlPath,

    [Parameter(Mandatory = $false)]
    [string]$OutputPath = './results',

    [Parameter(Mandatory = $false)]
    [ValidateSet('Html', 'Text', 'All')]
    [string]$Format = 'All',

    [Parameter(Mandatory = $false)]
    [ValidateRange(0, 100)]
    [int]$Threshold = 80,

    [Parameter(Mandatory = $false)]
    [switch]$IncludeUntested
)

# Ensure output directory exists
if (-not (Test-Path -LiteralPath $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

<#
.SYNOPSIS
    Parse coverage XML and extract coverage data.
#>
function ConvertFrom-CoverageXml {
    param([string]$XmlPath)

    # Load XML with settings that prevent attempting to load external DTDs
    $xmlSettings = New-Object System.Xml.XmlReaderSettings
    $xmlSettings.DtdProcessing = [System.Xml.DtdProcessing]::Ignore
    $xmlSettings.IgnoreComments = $true
    $xmlSettings.IgnoreWhitespace = $true
    
    $xml = New-Object System.Xml.XmlDocument
    $xmlReader = [System.Xml.XmlReader]::Create($XmlPath, $xmlSettings)
    try {
        $xml.Load($xmlReader)
    }
    finally {
        $xmlReader.Dispose()
    }
    
    $coverage = @()

    # Parse JACOCO format coverage (generated by Pester)
    # JACOCO format: report > package > class > method > counter (with LINE type)
    foreach ($package in $xml.SelectNodes('//package')) {
        $packageName = $package.GetAttribute('name')
        
        foreach ($class in $package.SelectNodes('class')) {
            $fileName = $class.GetAttribute('sourcefilename')
            $className = $class.GetAttribute('name')
            
            # Get full path
            $fullPath = if ($packageName -and $fileName) {
                "$packageName/$fileName"
            } else {
                $className
            }
            
            $fileData = @{
                Path           = $fullPath
                LineCount      = 0
                CoveredLines   = 0
                UncoveredLines = @()
                CoverageDetail = @()
                ClassName      = $className
            }

            # Get LINE counter from class level
            $lineCounter = $class.SelectSingleNode("counter[@type='LINE']")
            if ($lineCounter) {
                $missed = [int]$lineCounter.GetAttribute('missed')
                $covered = [int]$lineCounter.GetAttribute('covered')
                
                $fileData.LineCount = $missed + $covered
                $fileData.CoveredLines = $covered
                
                # For JACOCO format, we don't have detailed line-by-line coverage at class level
                # So we'll mark all as covered if covered count > 0
                for ($i = 0; $i -lt $fileData.LineCount; $i++) {
                    if ($i -lt $fileData.CoveredLines) {
                        $fileData.CoverageDetail += @{
                            LineNumber = $i + 1
                            Covered    = $true
                        }
                    }
                    else {
                        $fileData.CoverageDetail += @{
                            LineNumber = $i + 1
                            Covered    = $false
                        }
                        $fileData.UncoveredLines += ($i + 1)
                    }
                }
            }

            # Always set coverage percentage
            if ($fileData.LineCount -gt 0) {
                $fileData.Coverage = [math]::Round(($fileData.CoveredLines / $fileData.LineCount) * 100, 2)
            }
            else {
                $fileData.Coverage = 0
            }

            $coverage += $fileData
        }
    }

    return $coverage
}

<#
.SYNOPSIS
    Generate coverage statistics.
#>
function Get-CoverageStatistics {
    param([array]$CoverageData)

    $stats = @{
        TotalFiles       = $CoverageData.Count
        TotalLines       = 0
        TotalCovered     = 0
        TotalUncovered   = 0
        FileStats        = @()
        HighestCoverage  = 0
        LowestCoverage   = 100
        AverageCoverage  = 0
        ByStatus         = @{}
    }

    foreach ($file in $CoverageData) {
        $stats.TotalLines += $file.LineCount
        $stats.TotalCovered += $file.CoveredLines
        $stats.TotalUncovered += ($file.LineCount - $file.CoveredLines)

        # Track file-level stats
        $stats.FileStats += @{
            Path           = $file.Path
            Coverage       = $file.Coverage
            CoveredLines   = $file.CoveredLines
            UncoveredLines = $file.UncoveredLines.Count
            TotalLines     = $file.LineCount
        }

        # Track min/max
        if ($file.Coverage -gt $stats.HighestCoverage) {
            $stats.HighestCoverage = $file.Coverage
        }
        if ($file.Coverage -lt $stats.LowestCoverage -and $file.LineCount -gt 0) {
            $stats.LowestCoverage = $file.Coverage
        }
    }

    # Calculate averages
    if ($stats.TotalLines -gt 0) {
        $stats.OverallCoverage = [math]::Round(($stats.TotalCovered / $stats.TotalLines) * 100, 2)
    }
    else {
        $stats.OverallCoverage = 0
    }

    # Categorize by coverage percentage
    $stats.ByStatus = @{
        Excellent = @($stats.FileStats | Where-Object { $_.Coverage -ge 90 }).Count
        Good      = @($stats.FileStats | Where-Object { $_.Coverage -ge 75 -and $_.Coverage -lt 90 }).Count
        Fair      = @($stats.FileStats | Where-Object { $_.Coverage -ge 50 -and $_.Coverage -lt 75 }).Count
        Poor      = @($stats.FileStats | Where-Object { $_.Coverage -lt 50 }).Count
    }

    return $stats
}

<#
.SYNOPSIS
    Generate text-based coverage report.
#>
function New-TextCoverageReport {
    param(
        [array]$CoverageData,
        [hashtable]$Statistics,
        [string]$OutputPath,
        [int]$Threshold,
        [bool]$IncludeUntested
    )

    $reportPath = Join-Path -Path $OutputPath -ChildPath 'coverage-report.txt'
    $report = @()

    $report += "=" * 80
    $report += "PESTER CODE COVERAGE REPORT"
    $report += "=" * 80
    $report += ""
    $report += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $report += "Coverage Threshold: $Threshold%"
    $report += ""

    # Overall statistics
    $report += "OVERALL STATISTICS"
    $report += "-" * 80
    $report += "Overall Coverage:     $($Statistics.OverallCoverage)%"
    $report += "Total Files:          $($Statistics.TotalFiles)"
    $report += "Total Lines:          $($Statistics.TotalLines)"
    $report += "Covered Lines:        $($Statistics.TotalCovered)"
    $report += "Uncovered Lines:      $($Statistics.TotalUncovered)"
    $report += ""

    # Coverage by status
    $report += "COVERAGE DISTRIBUTION"
    $report += "-" * 80
    $report += "Excellent (90-100%):  $($Statistics.ByStatus.Excellent) files"
    $report += "Good (75-89%):        $($Statistics.ByStatus.Good) files"
    $report += "Fair (50-74%):        $($Statistics.ByStatus.Fair) files"
    $report += "Poor (<50%):          $($Statistics.ByStatus.Poor) files"
    $report += ""

    # Coverage threshold status
    $report += "THRESHOLD ANALYSIS"
    $report += "-" * 80
    if ($Statistics.OverallCoverage -ge $Threshold) {
        $report += "✓ Overall coverage MEETS threshold ($($Statistics.OverallCoverage)% >= $Threshold%)"
    }
    else {
        $report += "✗ Overall coverage BELOW threshold ($($Statistics.OverallCoverage)% < $Threshold%)"
        $report += "  Gap: $($Threshold - $Statistics.OverallCoverage)%"
    }
    $report += ""

    # Per-file breakdown
    $report += "FILE COVERAGE BREAKDOWN"
    $report += "-" * 80
    $report += "Sorted by coverage (highest to lowest):"
    $report += ""

    $sorted = $Statistics.FileStats | Sort-Object -Property Coverage -Descending

    foreach ($file in $sorted) {
        $status = switch ($file.Coverage) {
            { $_ -ge 90 } { "✓" }
            { $_ -ge 75 } { "→" }
            { $_ -ge 50 } { "!" }
            default { "✗" }
        }

        $filename = Split-Path -Leaf -Path $file.Path
        $report += "$status $filename"
        $report += "  Coverage: $($file.Coverage)% ($($file.CoveredLines)/$($file.TotalLines) lines)"

        if ($file.Coverage -lt $Threshold) {
            $report += "  WARNING: Below threshold by $($Threshold - $file.Coverage)%"
        }

        if ($IncludeUntested -and $file.UncoveredLines.Count -gt 0) {
            $maxShow = 10
            $uncovered = $file.UncoveredLines[0..([math]::Min($maxShow - 1, $file.UncoveredLines.Count - 1))]
            $report += "  Uncovered lines: $($uncovered -join ', ')"
            if ($file.UncoveredLines.Count -gt $maxShow) {
                $report += "  ... and $($file.UncoveredLines.Count - $maxShow) more"
            }
        }
        $report += ""
    }

    # Files below threshold
    $belowThreshold = $Statistics.FileStats | Where-Object { $_.Coverage -lt $Threshold } | Sort-Object -Property Coverage
    if ($belowThreshold.Count -gt 0) {
        $report += ""
        $report += "FILES BELOW THRESHOLD"
        $report += "-" * 80
        foreach ($file in $belowThreshold) {
            $filename = Split-Path -Leaf -Path $file.Path
            $report += "$filename - $($file.Coverage)% (Gap: $($Threshold - $file.Coverage)%)"
        }
    }

    $report += ""
    $report += "=" * 80

    # Write report
    $report | Out-File -LiteralPath $reportPath -Encoding utf8
    return $reportPath
}

<#
.SYNOPSIS
    Generate HTML coverage report.
#>
function New-HtmlCoverageReport {
    param(
        [array]$CoverageData,
        [hashtable]$Statistics,
        [string]$OutputPath,
        [int]$Threshold
    )

    $reportPath = Join-Path -Path $OutputPath -ChildPath 'coverage-report.html'
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

    # Build file rows
    $fileRows = @()
    $sorted = $Statistics.FileStats | Sort-Object -Property Coverage -Descending

    foreach ($file in $sorted) {
        $filename = Split-Path -Leaf -Path $file.Path
        $filepath = $file.Path
        
        $coverageValue = [double]$file.Coverage
        $coveredCount = [int]$file.CoveredLines
        $totalCount = [int]$file.TotalLines

        # Determine color based on coverage
        $color = switch ([double]$file.Coverage) {
            { $_ -ge 90 } { "#4CAF50" }  # Green
            { $_ -ge 75 } { "#2196F3" }  # Blue
            { $_ -ge 50 } { "#FF9800" }  # Orange
            default { "#F44336" }         # Red
        }

        $thresholdSymbol = if ([double]$file.Coverage -ge [double]$Threshold) { '✓' } else { '✗' }

        $row = "<tr>`n"
        $row += "    <td class=`"filename`">$([System.Web.HttpUtility]::HtmlEncode($filename))</td>`n"
        $row += "    <td>$coveredCount/$totalCount</td>`n"
        $row += "    <td>`n"
        $row += "        <div class=`"progress-bar`">`n"
        $row += "            <div class=`"progress-fill`" style=`"width: $coverageValue%; background-color: $color;`"></div>`n"
        $row += "        </div>`n"
        $row += "    </td>`n"
        $row += "    <td class=`"coverage`">$coverageValue%</td>`n"
        $row += "    <td class=`"threshold`">$thresholdSymbol</td>`n"
        $row += "</tr>`n"
        
        $fileRows += $row
    }

    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pester Code Coverage Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }

        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .header p {
            font-size: 1.1em;
            opacity: 0.9;
        }

        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 30px;
            background: #f5f5f5;
            border-bottom: 1px solid #ddd;
        }

        .summary-item {
            background: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .summary-item .label {
            color: #666;
            font-size: 0.9em;
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .summary-item .value {
            font-size: 2em;
            font-weight: bold;
            color: #333;
        }

        .summary-item .value.critical {
            color: #F44336;
        }

        .summary-item .value.warning {
            color: #FF9800;
        }

        .summary-item .value.success {
            color: #4CAF50;
        }

        .distribution {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }

        .distribution-item {
            text-align: center;
        }

        .distribution-item .count {
            font-size: 1.8em;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .distribution-item .label {
            font-size: 0.85em;
            color: #666;
        }

        .excellent { color: #4CAF50; }
        .good { color: #2196F3; }
        .fair { color: #FF9800; }
        .poor { color: #F44336; }

        .content {
            padding: 30px;
        }

        .section-title {
            font-size: 1.5em;
            color: #333;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 3px solid #667eea;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th {
            background: #667eea;
            color: white;
            padding: 15px;
            text-align: left;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.9em;
            letter-spacing: 1px;
        }

        td {
            padding: 12px 15px;
            border-bottom: 1px solid #eee;
        }

        tr:hover {
            background: #f9f9f9;
        }

        .filename {
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
            font-size: 0.9em;
            color: #333;
            font-weight: 500;
        }

        .coverage {
            font-weight: bold;
            min-width: 70px;
            text-align: center;
        }

        .threshold {
            text-align: center;
            font-size: 1.2em;
        }

        .progress-bar {
            height: 8px;
            background: #eee;
            border-radius: 4px;
            overflow: hidden;
            min-width: 100px;
        }

        .progress-fill {
            height: 100%;
            border-radius: 4px;
            transition: width 0.3s ease;
        }

        .threshold-info {
            background: #e3f2fd;
            border-left: 4px solid #2196F3;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 4px;
        }

        .threshold-info.warning {
            background: #fff3e0;
            border-left-color: #FF9800;
        }

        .threshold-info.critical {
            background: #ffebee;
            border-left-color: #F44336;
        }

        .meta {
            padding: 20px 30px;
            background: #f5f5f5;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 0.9em;
        }

        .legend {
            display: flex;
            gap: 30px;
            justify-content: center;
            margin: 20px 0;
            flex-wrap: wrap;
        }

        .legend-item {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .legend-color {
            width: 20px;
            height: 20px;
            border-radius: 3px;
        }

        @media (max-width: 768px) {
            .header h1 {
                font-size: 1.8em;
            }

            .summary {
                grid-template-columns: 1fr;
            }

            .distribution {
                grid-template-columns: repeat(2, 1fr);
            }

            table {
                font-size: 0.9em;
            }

            .coverage {
                min-width: auto;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Pester Code Coverage Report</h1>
            <p>Comprehensive test coverage analysis</p>
        </div>

        <div class="summary">
            <div class="summary-item">
                <div class="label">Overall Coverage</div>
                <div class="value $(if ($Statistics.OverallCoverage -lt $Threshold) { 'critical' } elseif ($Statistics.OverallCoverage -lt 85) { 'warning' } else { 'success' })">
                    $($Statistics.OverallCoverage)%
                </div>
            </div>
            <div class="summary-item">
                <div class="label">Files Analyzed</div>
                <div class="value">$($Statistics.TotalFiles)</div>
            </div>
            <div class="summary-item">
                <div class="label">Lines Covered</div>
                <div class="value">$($Statistics.TotalCovered)</div>
            </div>
            <div class="summary-item">
                <div class="label">Lines Uncovered</div>
                <div class="value critical">$($Statistics.TotalUncovered)</div>
            </div>

            <div class="distribution">
                <div class="distribution-item">
                    <div class="count excellent">$($Statistics.ByStatus.Excellent)</div>
                    <div class="label">Excellent</div>
                </div>
                <div class="distribution-item">
                    <div class="count good">$($Statistics.ByStatus.Good)</div>
                    <div class="label">Good</div>
                </div>
                <div class="distribution-item">
                    <div class="count fair">$($Statistics.ByStatus.Fair)</div>
                    <div class="label">Fair</div>
                </div>
                <div class="distribution-item">
                    <div class="count poor">$($Statistics.ByStatus.Poor)</div>
                    <div class="label">Poor</div>
                </div>
            </div>
        </div>

        <div class="content">
            <div class="threshold-info $(if ($Statistics.OverallCoverage -lt $Threshold) { if ($Statistics.OverallCoverage -lt 50) { 'critical' } else { 'warning' } })">
                <strong>Coverage Threshold:</strong> $Threshold%
                <br />
                $(if ($Statistics.OverallCoverage -ge $Threshold) { 
                    "✓ Overall coverage meets the threshold requirement"
                } else {
                    "✗ Coverage is below the $Threshold% threshold. Gap: $($Threshold - $Statistics.OverallCoverage)%"
                })
            </div>

            <h2 class="section-title">File Coverage Breakdown</h2>

            <div class="legend">
                <div class="legend-item">
                    <div class="legend-color" style="background: #4CAF50;"></div>
                    <span>Excellent (90-100%)</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #2196F3;"></div>
                    <span>Good (75-89%)</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #FF9800;"></div>
                    <span>Fair (50-74%)</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #F44336;"></div>
                    <span>Poor (&lt;50%)</span>
                </div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Coverage</th>
                        <th>Progress</th>
                        <th>Percentage</th>
                        <th>Threshold</th>
                    </tr>
                </thead>
                <tbody>
                    $($fileRows -join "`n")
                </tbody>
            </table>
        </div>

        <div class="meta">
            <p>Generated: $timestamp</p>
            <p>Coverage Tool: Pester | Format: CoverageGutters</p>
        </div>
    </div>
</body>
</html>
"@

    $html | Out-File -LiteralPath $reportPath -Encoding utf8
    return $reportPath
}

# ============================================================================
# Main Script Logic
# ============================================================================

try {
    Write-Host ""
    Write-Host "PSConfigResolver Code Coverage Report Generator" -ForegroundColor Cyan
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host ""

    # Parse coverage data
    Write-Host "  Parsing coverage data..." -NoNewline
    $coverageData = ConvertFrom-CoverageXml -XmlPath $CoverageXmlPath
    Write-Host " Done" -ForegroundColor Green

    # Generate statistics
    Write-Host "  Calculating statistics..." -NoNewline
    $stats = Get-CoverageStatistics -CoverageData $coverageData
    Write-Host " Done" -ForegroundColor Green

    # Generate reports
    if ($Format -in @('Text', 'All')) {
        Write-Host "  Generating text report..." -NoNewline
        $textReport = New-TextCoverageReport -CoverageData $coverageData -Statistics $stats `
            -OutputPath $OutputPath -Threshold $Threshold -IncludeUntested $IncludeUntested
        Write-Host " Done" -ForegroundColor Green
    }

    if ($Format -in @('Html', 'All')) {
        Write-Host "  Generating HTML report..." -NoNewline
        $htmlReport = New-HtmlCoverageReport -CoverageData $coverageData -Statistics $stats `
            -OutputPath $OutputPath -Threshold $Threshold
        Write-Host " Done" -ForegroundColor Green
    }

    Write-Host ""
    Write-Host "Coverage Summary:" -ForegroundColor Cyan
    Write-Host "  Overall Coverage: $($stats.OverallCoverage)%"
    Write-Host "  Files Analyzed: $($stats.TotalFiles)"
    Write-Host "  Total Lines: $($stats.TotalLines)"
    Write-Host "  Covered: $($stats.TotalCovered) | Uncovered: $($stats.TotalUncovered)"
    Write-Host ""

    if ($stats.OverallCoverage -lt $Threshold) {
        Write-Host "⚠ WARNING: Coverage is below the $Threshold% threshold!" -ForegroundColor Yellow
        Write-Host "  Gap: $($Threshold - $stats.OverallCoverage)%" -ForegroundColor Yellow
    }
    else {
        Write-Host "✓ Coverage meets the $Threshold% threshold" -ForegroundColor Green
    }

    Write-Host ""
    if ($Format -in @('Text', 'All')) {
        Write-Host "Reports generated:" -ForegroundColor Green
        Write-Host "  Text: $textReport"
    }
    if ($Format -in @('Html', 'All')) {
        Write-Host "  HTML: $htmlReport"
    }
    Write-Host ""
}
catch {
    Write-Host "Error generating coverage reports: $_" -ForegroundColor Red
    Write-Host "Stack trace: $($_.ScriptStackTrace)" -ForegroundColor Red
    exit 1
}
