name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
          Install-Module -Name ModuleTools -Force -SkipPublisherCheck -Scope CurrentUser
          Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          .\Invoke-Analysis.ps1 -ExitOnError

      - name: Build Module
        shell: pwsh
        run: |
          Invoke-MTBuild

      - name: Run Pester Tests
        shell: pwsh
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = "tests"
          $config.Run.Exit = $true
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = "src"
          $config.CodeCoverage.OutputPath = "results/coverage.xml"
          $config.CodeCoverage.OutputFormat = "CoverageGutters"
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config

      - name: Generate Coverage Report
        shell: pwsh
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"./results/coverage.xml" -targetdir:"./results/coverage-report" -reporttypes:Html

  codeql:
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'powershell'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2